.gitignore, en-GB.l20n, en-US.l20n, manifest.json
This will cause them to roll-out onto the live site :fireworks:
=> Merge demo set of translations to production

pt-BR.l20n
=> Progressing in Portuguese (Brazil)

en-GB.l20n, en-US.l20n, pt-BR.l20n
=> More work in pt-BR

en-GB.l20n, en-US.l20n, pt-BR.l20n
Anything else I can do to help you?
=> The last mile

pt-BR.l20n
=> missing pt-br translation "or here" = "ou aqui"

en-GB.l20n, en-US.l20n, fr.l20n
Hi there,
Here is a partial translation into french language of Coggle web application, I've tried to translate the most **important** features and things in my opinion. As now, the only things which aren't translated are : 
- Coggle facts (I will do it asap)
- Some orgs-* things on their landing page. (Also asap)
- Diagram tooltips (and maybe other kind of things).
I have only one question, considering this from the en-US : 
```
/* diagram tooltips */
<context-dragclick "drag to move, click to edit">
<context-dragclickfollow "drag to move, click to edit, {{ $followLinkKey }} + click to follow links">
<context-remove-branch-alt "remove this branch: release [alt] to add branch instead">
<context-insert-branch "insert text: release [shift] to add branch instead">
<context-squash-branch …
```
=> Partial french translation

en-GB.l20n, en-US.l20n, fr.l20n
Hi there,
As promised, here is the complete french translation ! (I hope I haven't forgotten something... :sweat_smile:)
I hope that it can helps you to get more **french** users !
Except the french translation, this pull request contains some typo fixed in original files!
Thanks in advance, guys!
=> Complete french translation

en-GB.l20n, en-US.l20n
* Make some existing content translatable (some notification messages and access control sliders).
* Add translations for some new content on the homepage
=> Add more translations

ja-JP.l20n, manifest.json
I created ja-JP.l20n file and translated front page content.
=> Create ja jp

ja.l20n
=> Translate about coggle

ja.l20n
=> Translate list and hints

ja.l20n
=> Translate sidebar contents

ja.l20n
=> Translate dialogs

ja.l20n
=> Translate coggle facts

en-GB.l20n, en-US.l20n, fr.l20n, pt-BR.l20n
=> remove more: links from fact translations

ja.l20n
=> Translate supports contents

ja.l20n
=> Translate sidebar sc markdown

manifest.json, zh-CN.l20n
=> Add zh-CN translation

ja.l20n
Translate organization parts without organization landing page.
=> Translate organization without landing

zh-CN.l20n
download dialog, access control, notification msg, drag-drop.
=> More zh-cn translation

manifest.json, sv-SE.l20n
cc @sodper: I'd love to test out & merge what you have already to the live site – is that OK?
=> Swedish translations!

en-GB.l20n, en-US.l20n
en US/GB translations for updated share dialog for [Open Coggle](http://bloggle.coggle.it/open-coggles/) sharing.
=> add translations for Open Coggle sharing

ja.l20n
Japanese tweets about coggle incleases, I think :)
=> [ja] Update translations to 1daa44e56fc8b90a5c333a03832ff5824a668c68

ru.l20n
Hello! I am a user of your services from Russia. I want in the next time to fully translate the file with the Russian translation of the Russian language!
=> update russian translation file

ja.l20n
Translated fontpage content after a long interval :)
=> Update frontpage content ja.l20n

ja.l20n
Merge latest U.S. content(default) and add a little new translations.
=> Merge latest US content ja.l20n

ja.l20n
=> Add frontpage and other translations

ja.l20n
Add translation for a well-seen parts.
=> Update gallery message and something else

de-DE.l20n
added source language-file for German
=> improving new language de-DE

pt-BR.l20n
Added portugues instruction and some translations.
=> Update on pt-BR.l20n

it.l20n, manifest.json
Hi there, I found Coggle being a very nice and helpful software for mind mapping, hope my contribution helps to spread this fantastic tool among Italian users.
=> Traslation to italian language

it-IT.emails.l20n, it.l20n
Hey, finally had time to translate also the email. If you can send me those emails to "anatolieghebea@gmail.com", I'll check for any errors!
=> Italian traslation for coggle emails

fr.l20n
- Fixed some errors and typos
- Completely translated what was not yet done
=> hikatanguy - full FR translation

fa.emails.l20n, fa.l20n, manifest.json
I Just add Farsi (Persian) Language for coggle.it,
I will Update it very soon but it's my first version of translation.
=> first version of persian language

en.ftl, ja.ftl, ru.ftl
I have emailed you about the areas where I would like an ID to be added, so please consider it. I sent the email from neko081877@gmail.com to translate@coggle.it.
=> Fixed areas where there were missing translations or inconsistencies between the translated content and where it was displayed.

ko.ftl
Hello! I am bilingual in Japanese and Korean.
I would like to introduce this service to my Korean friends and contribute to the Korean translation.
I will start by translating up to 400 lines and will submit a PR. I plan to translate the remaining lines gradually.
=> [WIP] Translation into Korean

vi.ftl
Dear Coggle team,
I have translated and proofread most of the text into Vietnamese (some parts are not translated yet and will be updated later).  
I would like to contribute to this project to support Vietnamese users.  
If you have any feedback or suggestions, please contact me via email: annent1223@gmail.com.
Best regards,
Anxie-y
=> Create Vietnamese translation

ro.ftl
Hi again,
This is the second pull request from my Romanian translation for the app. Everything up to line 506 in file `ro.ftl` is covered here, so I'm essentially halfway there.
I have no questions about what I've encountered so far and I'll come up with the rest soon.
Thanks! :)
=> Updated Romanian translation (halfway there)
